WITH RESULT AS (SELECT V.CUSTOMER_ID FROM VISITS V
LEFT JOIN TRANSACTIONS T
ON V.VISIT_ID=T.VISIT_ID
WHERE T.VISIT_ID IS NULL
) 

SELECT CUSTOMER_ID,COUNT(*) AS COUNT_NO_TRANS FROM RESULT
GROUP BY CUSTOMER_ID;
