SELECT A.ID
FROM WEATHER A
INNER JOIN (
    SELECT TEMPERATURE,DATE_ADD(RECORDDATE, INTERVAL 1 DAY) AS RECORD_DATE FROM WEATHER
) B 
ON A.RECORDDATE=B.RECORD_DATE
WHERE A.TEMPERATURE>B.TEMPERATURE;
